@ECHO OFF
IF NOT DEFINED STRESSTOOL_DEPLOYMENT_DIR (
	SET STRESSTOOL_DEPLOYMENT_DIR=.\Deployment
)

RMDIR /S /Q "%STRESSTOOL_DEPLOYMENT_DIR%"
MKDIR "%STRESSTOOL_DEPLOYMENT_DIR%"

COPY "%~dp0x64\Release\StressTool_64.exe" "%STRESSTOOL_DEPLOYMENT_DIR%"
COPY "%~dp0Release\StressTool_32.exe" "%STRESSTOOL_DEPLOYMENT_DIR%"